// main toolbar
export const TB_MAIN = "#tbMain"
export const BTN_SHOW_SECURITY_PRINCIPALS = "#btnShowSecurityPrincipals"
export const BTN_SHOW_SECURE_OBJECTS = "#btnShowSecureObjects"

export const DLG_SELECT_FILE = "#dlgSelectFile"
export const TREEVIEW_SELECT_FILE = "#tvSelectFile"
export const DLG_SAVE_AS = "#dlgSaveAs"
export const TREEVIEW_SAVE_AS = "#tvSaveAs"
export const TXT_SAVE_AS_NAME = "#txtSaveAsName"

// security principals
export const SP_VIEW = "#spView"
export const SP_SPLITTER = "#spSpltr"
export const SP_GRID = "#spGrd"
export const SP_TXT_GRD_FILTER = "#spTxtGrdFilter"
export const SP_EDITOR = "#spEditor"
export const SP_EDITOR_ERROR = "#spEditorError"
export const SP_LISTBOX_MEMBER_OF = "#spLbMemberOf"
export const SP_LISTBOX_NOT_MEMBER_OF = "#spLbNotMemberOf"
export const SP_LISTBOX_MEMBERS = "#spLbMembers"
export const SP_LISTBOX_NON_MEMBERS = "#spLbNonMembers"
export const SP_TXT_MEMBER_OF_FILTER = "#spTxtMemberOfFilter"
export const SP_TXT_NOT_MEMBER_OF_FILTER = "#spTxtNotMemberOfFilter"
export const SP_TXT_MEMBERS_FILTER = "#spTxtMembersFilter"
export const SP_TXT_NON_MEMBERS_FILTER = "#spTxtNonMembersFilter"
export const SP_TREELIST_GROUP_HIERARCHY = "#spTlGroupHierarchy"

// secure objects
export const SO_VIEW = "#soView"
export const SO_SPLITTER = "#soSpltr"
export const SO_TREEVIEW = "#soTv"
export const SO_EDITOR = "#soEditor"
export const SO_EDITOR_ERROR = "#soEditorError"
export const SO_GRD_DACL = "#soGrdDacl"
export const SO_GRD_SACL = "#soGrdSacl"
